### ISSUE TITLE
Double Tipping

### ISSUE THREAD

**Issue by lilynut** [shredding/stellar-bot#20]
I tipped from my IOS phone and it double tipped the person.

**Comment by shredding** [comment]
The app restarted because it couldn't handle the xlmpool inflation deposit. This is fixed here: https://github.com/shredding/stellar-bot/commit/3f6dc250b9d83af0cf240fa2de664f89c1ec04e4

The restart polled the comments again and wasn't aware that they were already tipped.

Therefore I need to track better which tips are already made and this will be done here: https://github.com/shredding/stellar-bot/issues/18

As long as the app does not restart you are fine and there are no known bugs - but I will address this ASAP.

**Comment by lilynut** [comment]
Thanks
